// Load environment variables FIRST before any other imports
import { config } from "dotenv"
import { resolve } from "path"

config({ path: resolve(process.cwd(), ".env") })

// Create database connection directly to avoid import timing issues
import { drizzle } from "drizzle-orm/postgres-js"
import postgres from "postgres"
import * as schema from "./schema"
import { eq } from "drizzle-orm"

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL environment variable is not set")
}

const connectionString = process.env.DATABASE_URL
const client = postgres(connectionString)
const db = drizzle(client, { schema })

import { colleges, courses } from "./schema"

// Comprehensive list of major Indian colleges with all comparison fields
const comprehensiveColleges = [
  // Top IITs and Engineering Colleges
  {
    name: "Indian Institute of Technology Delhi",
    slug: "iit-delhi",
    location: "Hauz Khas, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    description: "IIT Delhi is one of the premier engineering institutes in India, established in 1961. It offers undergraduate, postgraduate, and doctoral programs in various engineering and science disciplines.",
    ranking: 2,
    establishedYear: 1961,
    accreditation: "AICTE, UGC",
    ownership: "Government",
    campusSize: "320 acres",
    totalStudents: 8500,
    hostelFees: 120000,
    averagePackage: 2200000,
    highestPackage: 15000000,
    entranceExams: ["JEE Advanced", "GATE"],
    website: "https://www.iitd.ac.in",
    email: "admin@iitd.ac.in",
    phone: "+91-11-26591753",
    isAcademicAlliance: false,
  },
  {
    name: "Indian Institute of Technology Bombay",
    slug: "iit-bombay",
    location: "Powai, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    description: "IIT Bombay is one of the top engineering institutes in India, known for excellence in engineering education and research.",
    ranking: 3,
    establishedYear: 1958,
    accreditation: "AICTE, UGC",
    ownership: "Government",
    campusSize: "550 acres",
    totalStudents: 10000,
    hostelFees: 125000,
    averagePackage: 2100000,
    highestPackage: 18000000,
    entranceExams: ["JEE Advanced", "GATE"],
    website: "https://www.iitb.ac.in",
    email: "info@iitb.ac.in",
    phone: "+91-22-25722545",
    isAcademicAlliance: false,
  },
  {
    name: "Indian Institute of Technology Madras",
    slug: "iit-madras",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    description: "IIT Madras is a premier technical institute offering world-class education in engineering and technology.",
    ranking: 1,
    establishedYear: 1959,
    accreditation: "AICTE, UGC",
    ownership: "Government",
    campusSize: "620 acres",
    totalStudents: 9000,
    hostelFees: 115000,
    averagePackage: 2000000,
    highestPackage: 16000000,
    entranceExams: ["JEE Advanced", "GATE"],
    website: "https://www.iitm.ac.in",
    email: "admin@iitm.ac.in",
    phone: "+91-44-22578500",
    isAcademicAlliance: false,
  },
  {
    name: "Birla Institute of Technology and Science",
    slug: "bits-pilani",
    location: "Pilani, Rajasthan",
    city: "Pilani",
    state: "Rajasthan",
    description: "BITS Pilani is a premier private technical university known for its innovative curriculum and excellent placements.",
    ranking: 15,
    establishedYear: 1964,
    accreditation: "UGC",
    ownership: "Private",
    campusSize: "328 acres",
    totalStudents: 12000,
    hostelFees: 180000,
    averagePackage: 1800000,
    highestPackage: 12000000,
    entranceExams: ["BITSAT"],
    website: "https://www.bits-pilani.ac.in",
    email: "admissions@pilani.bits-pilani.ac.in",
    phone: "+91-1596-242210",
    isAcademicAlliance: false,
  },
  {
    name: "Vellore Institute of Technology",
    slug: "vit-vellore",
    location: "Vellore, Tamil Nadu",
    city: "Vellore",
    state: "Tamil Nadu",
    description: "VIT is a leading private university offering quality education in engineering, management, and other disciplines.",
    ranking: 8,
    establishedYear: 1984,
    accreditation: "UGC, AICTE",
    ownership: "Private",
    campusSize: "372 acres",
    totalStudents: 35000,
    hostelFees: 200000,
    averagePackage: 800000,
    highestPackage: 4500000,
    entranceExams: ["VITEEE"],
    website: "https://vit.ac.in",
    email: "info@vit.ac.in",
    phone: "+91-416-2243091",
    isAcademicAlliance: false,
  },
  {
    name: "SRM Institute of Science and Technology",
    slug: "srm-university",
    location: "Kattankulathur, Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    description: "SRM is a leading private university offering diverse programs in engineering, management, medicine, and more.",
    ranking: 35,
    establishedYear: 1985,
    accreditation: "UGC, AICTE",
    ownership: "Private",
    campusSize: "250 acres",
    totalStudents: 50000,
    hostelFees: 150000,
    averagePackage: 600000,
    highestPackage: 3500000,
    entranceExams: ["SRMJEE"],
    website: "https://www.srmist.edu.in",
    email: "admissions@srmist.edu.in",
    phone: "+91-44-27455713",
    isAcademicAlliance: false,
  },
  {
    name: "Manipal Academy of Higher Education",
    slug: "manipal-university",
    location: "Manipal, Karnataka",
    city: "Manipal",
    state: "Karnataka",
    description: "MAHE is a leading private university offering programs in engineering, medicine, management, and other fields.",
    ranking: 12,
    establishedYear: 1953,
    accreditation: "UGC",
    ownership: "Private",
    campusSize: "313 acres",
    totalStudents: 28000,
    hostelFees: 220000,
    averagePackage: 750000,
    highestPackage: 4000000,
    entranceExams: ["MET"],
    website: "https://manipal.edu",
    email: "info@manipal.edu",
    phone: "+91-820-2922400",
    isAcademicAlliance: false,
  },
  {
    name: "Amity University",
    slug: "amity-university-noida",
    location: "Noida, Uttar Pradesh",
    city: "Noida",
    state: "Uttar Pradesh",
    description: "Amity University is a leading private university offering comprehensive programs across multiple disciplines.",
    ranking: 45,
    establishedYear: 2005,
    accreditation: "UGC",
    ownership: "Private",
    campusSize: "60 acres",
    totalStudents: 15000,
    hostelFees: 180000,
    averagePackage: 550000,
    highestPackage: 3000000,
    entranceExams: ["Amity JEE"],
    website: "https://www.amity.edu",
    email: "admission@amity.edu",
    phone: "+91-120-4392000",
    isAcademicAlliance: false,
  },
  {
    name: "Lovely Professional University",
    slug: "lpu-jalandhar",
    location: "Phagwara, Punjab",
    city: "Phagwara",
    state: "Punjab",
    description: "LPU is one of India's largest private universities offering diverse programs in engineering, management, and more.",
    ranking: 50,
    establishedYear: 2005,
    accreditation: "UGC",
    ownership: "Private",
    campusSize: "600 acres",
    totalStudents: 30000,
    hostelFees: 140000,
    averagePackage: 500000,
    highestPackage: 2500000,
    entranceExams: ["LPUNEST"],
    website: "https://www.lpu.in",
    email: "admissions@lpu.co.in",
    phone: "+91-1824-517777",
    isAcademicAlliance: false,
  },
  {
    name: "National Institute of Technology Warangal",
    slug: "nit-warangal",
    location: "Warangal, Telangana",
    city: "Warangal",
    state: "Telangana",
    description: "NIT Warangal is a premier engineering institute offering quality technical education.",
    ranking: 20,
    establishedYear: 1959,
    accreditation: "AICTE",
    ownership: "Government",
    campusSize: "250 acres",
    totalStudents: 6000,
    hostelFees: 80000,
    averagePackage: 1200000,
    highestPackage: 8000000,
    entranceExams: ["JEE Main"],
    website: "https://www.nitw.ac.in",
    email: "director@nitw.ac.in",
    phone: "+91-870-2459191",
    isAcademicAlliance: false,
  },
  
  // Top Management Colleges
  {
    name: "Indian Institute of Management Ahmedabad",
    slug: "iim-ahmedabad",
    location: "Ahmedabad, Gujarat",
    city: "Ahmedabad",
    state: "Gujarat",
    description: "IIM Ahmedabad is India's premier management institute, consistently ranked #1 for MBA programs.",
    ranking: 1,
    establishedYear: 1961,
    accreditation: "AICTE",
    ownership: "Government",
    campusSize: "102 acres",
    totalStudents: 1200,
    hostelFees: 150000,
    averagePackage: 3500000,
    highestPackage: 60000000,
    entranceExams: ["CAT"],
    website: "https://www.iima.ac.in",
    email: "admission@iima.ac.in",
    phone: "+91-79-66323456",
    isAcademicAlliance: false,
  },
  {
    name: "Indian Institute of Management Bangalore",
    slug: "iim-bangalore",
    location: "Bannerghatta Road, Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    description: "IIM Bangalore is one of India's top management institutes, known for excellence in business education.",
    ranking: 2,
    establishedYear: 1973,
    accreditation: "AICTE",
    ownership: "Government",
    campusSize: "100 acres",
    totalStudents: 1100,
    hostelFees: 160000,
    averagePackage: 3200000,
    highestPackage: 55000000,
    entranceExams: ["CAT"],
    website: "https://www.iimb.ac.in",
    email: "pgp@iimb.ac.in",
    phone: "+91-80-26993000",
    isAcademicAlliance: false,
  },
  {
    name: "Indian Institute of Management Calcutta",
    slug: "iim-calcutta",
    location: "Joka, Kolkata",
    city: "Kolkata",
    state: "West Bengal",
    description: "IIM Calcutta is India's first IIM and a leading management institute with global recognition.",
    ranking: 3,
    establishedYear: 1961,
    accreditation: "AICTE",
    ownership: "Government",
    campusSize: "135 acres",
    totalStudents: 1000,
    hostelFees: 145000,
    averagePackage: 3100000,
    highestPackage: 50000000,
    entranceExams: ["CAT"],
    website: "https://www.iimcal.ac.in",
    email: "pgp@iimcal.ac.in",
    phone: "+91-33-24678300",
    isAcademicAlliance: false,
  },
  {
    name: "XLRI Xavier School of Management",
    slug: "xlri-jamshedpur",
    location: "Jamshedpur, Jharkhand",
    city: "Jamshedpur",
    state: "Jharkhand",
    description: "XLRI is one of India's oldest and most prestigious business schools, known for its HR and business programs.",
    ranking: 5,
    establishedYear: 1949,
    accreditation: "AICTE",
    ownership: "Private",
    campusSize: "50 acres",
    totalStudents: 900,
    hostelFees: 200000,
    averagePackage: 3000000,
    highestPackage: 45000000,
    entranceExams: ["XAT", "GMAT"],
    website: "https://www.xlri.ac.in",
    email: "admission@xlri.ac.in",
    phone: "+91-657-2225506",
    isAcademicAlliance: false,
  },
  {
    name: "Indian School of Business",
    slug: "isb-hyderabad",
    location: "Gachibowli, Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    description: "ISB is a premier business school offering world-class management education with global partnerships.",
    ranking: 4,
    establishedYear: 2001,
    accreditation: "AACSB",
    ownership: "Private",
    campusSize: "260 acres",
    totalStudents: 800,
    hostelFees: 250000,
    averagePackage: 3400000,
    highestPackage: 65000000,
    entranceExams: ["GMAT", "GRE"],
    website: "https://www.isb.edu",
    email: "pgp@isb.edu",
    phone: "+91-40-23007000",
    isAcademicAlliance: false,
  },
  {
    name: "SP Jain Institute of Management and Research",
    slug: "spjimr-mumbai",
    location: "Andheri, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    description: "SPJIMR is a leading B-school known for its innovative pedagogy and excellent placements.",
    ranking: 10,
    establishedYear: 1981,
    accreditation: "AICTE",
    ownership: "Private",
    campusSize: "45 acres",
    totalStudents: 600,
    hostelFees: 180000,
    averagePackage: 2800000,
    highestPackage: 40000000,
    entranceExams: ["CAT", "GMAT"],
    website: "https://www.spjimr.org",
    email: "pgdm@spjimr.org",
    phone: "+91-22-61454200",
    isAcademicAlliance: false,
  },
  {
    name: "Management Development Institute",
    slug: "mdi-gurgaon",
    location: "Gurgaon, Haryana",
    city: "Gurgaon",
    state: "Haryana",
    description: "MDI Gurgaon is a premier B-school offering quality management education with strong industry connections.",
    ranking: 12,
    establishedYear: 1973,
    accreditation: "AICTE",
    ownership: "Private",
    campusSize: "37 acres",
    totalStudents: 700,
    hostelFees: 190000,
    averagePackage: 2600000,
    highestPackage: 35000000,
    entranceExams: ["CAT"],
    website: "https://www.mdi.ac.in",
    email: "pgpm@mdi.ac.in",
    phone: "+91-124-4560000",
    isAcademicAlliance: false,
  },
  {
    name: "ISBR Business School",
    slug: "isbr-business-school-bangalore",
    location: "Electronic City, Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    description: "ISBR is a leading business school offering MBA and PGDM programs with industry-focused curriculum.",
    ranking: 60,
    establishedYear: 1990,
    accreditation: "AICTE",
    ownership: "Private",
    campusSize: "5 acres",
    totalStudents: 500,
    hostelFees: 120000,
    averagePackage: 800000,
    highestPackage: 1500000,
    entranceExams: ["CAT", "MAT", "CMAT"],
    website: "https://www.isbr.in",
    email: "admissions@isbr.in",
    phone: "+91-80-25734999",
    isAcademicAlliance: true,
  },
  
  // Medical Colleges
  {
    name: "All India Institute of Medical Sciences",
    slug: "aiims-delhi",
    location: "Ansari Nagar, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    description: "AIIMS Delhi is India's premier medical institute, offering world-class medical education and healthcare.",
    ranking: 1,
    establishedYear: 1956,
    accreditation: "MCI",
    ownership: "Government",
    campusSize: "350 acres",
    totalStudents: 2000,
    hostelFees: 60000,
    averagePackage: 1200000,
    highestPackage: 5000000,
    entranceExams: ["NEET"],
    website: "https://www.aiims.edu",
    email: "academic@aiims.edu",
    phone: "+91-11-26588500",
    isAcademicAlliance: false,
  },
  {
    name: "Christian Medical College",
    slug: "cmc-vellore",
    location: "Vellore, Tamil Nadu",
    city: "Vellore",
    state: "Tamil Nadu",
    description: "CMC Vellore is a premier medical college known for excellence in medical education and patient care.",
    ranking: 2,
    establishedYear: 1900,
    accreditation: "MCI",
    ownership: "Private",
    campusSize: "200 acres",
    totalStudents: 1500,
    hostelFees: 100000,
    averagePackage: 1000000,
    highestPackage: 4000000,
    entranceExams: ["NEET"],
    website: "https://www.cmch-vellore.edu",
    email: "admissions@cmch-vellore.edu",
    phone: "+91-416-2222102",
    isAcademicAlliance: false,
  },
  {
    name: "Armed Forces Medical College",
    slug: "afmc-pune",
    location: "Pune, Maharashtra",
    city: "Pune",
    state: "Maharashtra",
    description: "AFMC is a premier medical college under the Ministry of Defence, training medical officers for armed forces.",
    ranking: 5,
    establishedYear: 1948,
    accreditation: "MCI",
    ownership: "Government",
    campusSize: "100 acres",
    totalStudents: 800,
    hostelFees: 50000,
    averagePackage: 800000,
    highestPackage: 3000000,
    entranceExams: ["NEET"],
    website: "https://www.afmc.nic.in",
    email: "afmc@nic.in",
    phone: "+91-20-26306000",
    isAcademicAlliance: false,
  },
  
  // Law Colleges
  {
    name: "National Law School of India University",
    slug: "nlsiu-bangalore",
    location: "Nagarbhavi, Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    description: "NLSIU Bangalore is India's premier law school, consistently ranked #1 for legal education.",
    ranking: 1,
    establishedYear: 1987,
    accreditation: "UGC",
    ownership: "Government",
    campusSize: "23 acres",
    totalStudents: 600,
    hostelFees: 80000,
    averagePackage: 1500000,
    highestPackage: 25000000,
    entranceExams: ["CLAT"],
    website: "https://www.nls.ac.in",
    email: "admissions@nls.ac.in",
    phone: "+91-80-23160531",
    isAcademicAlliance: false,
  },
  {
    name: "National Law University",
    slug: "nlu-delhi",
    location: "Dwarka, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    description: "NLU Delhi is a premier law university offering quality legal education with modern infrastructure.",
    ranking: 2,
    establishedYear: 2008,
    accreditation: "UGC",
    ownership: "Government",
    campusSize: "50 acres",
    totalStudents: 800,
    hostelFees: 90000,
    averagePackage: 1400000,
    highestPackage: 20000000,
    entranceExams: ["AILET"],
    website: "https://www.nludelhi.ac.in",
    email: "admissions@nludelhi.ac.in",
    phone: "+91-11-28034255",
    isAcademicAlliance: false,
  },
  
  // Design Colleges
  {
    name: "National Institute of Design",
    slug: "nid-ahmedabad",
    location: "Ahmedabad, Gujarat",
    city: "Ahmedabad",
    state: "Gujarat",
    description: "NID is India's premier design institute, offering world-class education in various design disciplines.",
    ranking: 1,
    establishedYear: 1961,
    accreditation: "AICTE",
    ownership: "Government",
    campusSize: "63 acres",
    totalStudents: 500,
    hostelFees: 70000,
    averagePackage: 800000,
    highestPackage: 3000000,
    entranceExams: ["NID DAT"],
    website: "https://www.nid.edu",
    email: "admissions@nid.edu",
    phone: "+91-79-26629696",
    isAcademicAlliance: false,
  },
  {
    name: "Pearl Academy",
    slug: "pearl-academy-delhi",
    location: "Naraina, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    description: "Pearl Academy is a leading design institute offering programs in fashion, design, and media.",
    ranking: 5,
    establishedYear: 1993,
    accreditation: "UGC",
    ownership: "Private",
    campusSize: "2 acres",
    totalStudents: 2000,
    hostelFees: 150000,
    averagePackage: 600000,
    highestPackage: 2000000,
    entranceExams: ["Pearl Academy Entrance"],
    website: "https://www.pearlacademy.com",
    email: "admissions@pearlacademy.com",
    phone: "+91-11-47111111",
    isAcademicAlliance: false,
  },
  
  // Additional Top Colleges
  {
    name: "Jawaharlal Nehru University",
    slug: "jnu-delhi",
    location: "New Delhi",
    city: "New Delhi",
    state: "Delhi",
    description: "JNU is a premier public university known for excellence in social sciences, languages, and international studies.",
    ranking: 3,
    establishedYear: 1969,
    accreditation: "UGC",
    ownership: "Government",
    campusSize: "1000 acres",
    totalStudents: 8000,
    hostelFees: 30000,
    averagePackage: 500000,
    highestPackage: 2000000,
    entranceExams: ["JNUEE"],
    website: "https://www.jnu.ac.in",
    email: "admissions@jnu.ac.in",
    phone: "+91-11-26704000",
    isAcademicAlliance: false,
  },
  {
    name: "Delhi University",
    slug: "du-delhi",
    location: "North Campus, Delhi",
    city: "New Delhi",
    state: "Delhi",
    description: "Delhi University is one of India's largest and most prestigious universities with excellent academic programs.",
    ranking: 11,
    establishedYear: 1922,
    accreditation: "UGC",
    ownership: "Government",
    campusSize: "69 acres",
    totalStudents: 400000,
    hostelFees: 40000,
    averagePackage: 600000,
    highestPackage: 1500000,
    entranceExams: ["DUET"],
    website: "https://www.du.ac.in",
    email: "info@du.ac.in",
    phone: "+91-11-27667891",
    isAcademicAlliance: false,
  },
  {
    name: "Banaras Hindu University",
    slug: "bhu-varanasi",
    location: "Varanasi, Uttar Pradesh",
    city: "Varanasi",
    state: "Uttar Pradesh",
    description: "BHU is a premier central university offering diverse programs in arts, sciences, engineering, and medicine.",
    ranking: 6,
    establishedYear: 1916,
    accreditation: "UGC",
    ownership: "Government",
    campusSize: "1300 acres",
    totalStudents: 30000,
    hostelFees: 50000,
    averagePackage: 700000,
    highestPackage: 1800000,
    entranceExams: ["BHU UET"],
    website: "https://www.bhu.ac.in",
    email: "info@bhu.ac.in",
    phone: "+91-542-2368554",
    isAcademicAlliance: false,
  },
  {
    name: "Jadavpur University",
    slug: "ju-kolkata",
    location: "Kolkata, West Bengal",
    city: "Kolkata",
    state: "West Bengal",
    description: "Jadavpur University is a premier public university known for excellence in engineering and arts.",
    ranking: 9,
    establishedYear: 1955,
    accreditation: "UGC, AICTE",
    ownership: "Government",
    campusSize: "58 acres",
    totalStudents: 12000,
    hostelFees: 60000,
    averagePackage: 800000,
    highestPackage: 2000000,
    entranceExams: ["WBJEE"],
    website: "https://www.jaduniv.edu.in",
    email: "info@jaduniv.edu.in",
    phone: "+91-33-24146666",
    isAcademicAlliance: false,
  },
  {
    name: "Anna University",
    slug: "anna-university-chennai",
    location: "Guindy, Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    description: "Anna University is a premier technical university offering quality engineering and technology programs.",
    ranking: 18,
    establishedYear: 1978,
    accreditation: "UGC, AICTE",
    ownership: "Government",
    campusSize: "185 acres",
    totalStudents: 15000,
    hostelFees: 70000,
    averagePackage: 750000,
    highestPackage: 1800000,
    entranceExams: ["TANCET"],
    website: "https://www.annauniv.edu",
    email: "info@annauniv.edu",
    phone: "+91-44-22351723",
    isAcademicAlliance: false,
  },
  {
    name: "Punjab Engineering College",
    slug: "pec-chandigarh",
    location: "Chandigarh",
    city: "Chandigarh",
    state: "Punjab",
    description: "PEC is a premier engineering institute offering quality technical education with excellent placements.",
    ranking: 25,
    establishedYear: 1921,
    accreditation: "AICTE",
    ownership: "Government",
    campusSize: "146 acres",
    totalStudents: 3000,
    hostelFees: 80000,
    averagePackage: 900000,
    highestPackage: 2200000,
    entranceExams: ["JEE Main"],
    website: "https://www.pec.ac.in",
    email: "info@pec.ac.in",
    phone: "+91-172-2753051",
    isAcademicAlliance: false,
  },
  {
    name: "Thapar Institute of Engineering and Technology",
    slug: "thapar-university",
    location: "Patiala, Punjab",
    city: "Patiala",
    state: "Punjab",
    description: "Thapar University is a leading private engineering institute known for quality education and placements.",
    ranking: 30,
    establishedYear: 1956,
    accreditation: "UGC, AICTE",
    ownership: "Private",
    campusSize: "250 acres",
    totalStudents: 8000,
    hostelFees: 160000,
    averagePackage: 1000000,
    highestPackage: 2500000,
    entranceExams: ["JEE Main"],
    website: "https://www.thapar.edu",
    email: "admissions@thapar.edu",
    phone: "+91-175-2393021",
    isAcademicAlliance: false,
  },
  {
    name: "Symbiosis International University",
    slug: "siu-pune",
    location: "Lavale, Pune",
    city: "Pune",
    state: "Maharashtra",
    description: "SIU is a leading private university offering diverse programs in management, law, and other disciplines.",
    ranking: 22,
    establishedYear: 1971,
    accreditation: "UGC",
    ownership: "Private",
    campusSize: "300 acres",
    totalStudents: 25000,
    hostelFees: 200000,
    averagePackage: 850000,
    highestPackage: 2000000,
    entranceExams: ["SNAP", "SET"],
    website: "https://www.siu.edu.in",
    email: "admission@symbiosis.ac.in",
    phone: "+91-20-25671905",
    isAcademicAlliance: false,
  },
  {
    name: "Christ University",
    slug: "christ-university-bangalore",
    location: "Hosur Road, Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    description: "Christ University is a premier private university offering quality education across multiple disciplines.",
    ranking: 28,
    establishedYear: 1969,
    accreditation: "UGC",
    ownership: "Private",
    campusSize: "75 acres",
    totalStudents: 20000,
    hostelFees: 180000,
    averagePackage: 700000,
    highestPackage: 1800000,
    entranceExams: ["CUET"],
    website: "https://www.christuniversity.in",
    email: "admission@christuniversity.in",
    phone: "+91-80-40129000",
    isAcademicAlliance: false,
  },
  {
    name: "Jamia Millia Islamia",
    slug: "jmi-delhi",
    location: "Jamia Nagar, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    description: "JMI is a central university offering diverse programs in engineering, management, and humanities.",
    ranking: 14,
    establishedYear: 1920,
    accreditation: "UGC",
    ownership: "Government",
    campusSize: "198 acres",
    totalStudents: 20000,
    hostelFees: 50000,
    averagePackage: 650000,
    highestPackage: 1500000,
    entranceExams: ["JMI Entrance"],
    website: "https://www.jmi.ac.in",
    email: "info@jmi.ac.in",
    phone: "+91-11-26981717",
    isAcademicAlliance: false,
  },
  
  // More IITs
  {
    name: "Indian Institute of Technology Kanpur",
    slug: "iit-kanpur",
    location: "Kanpur, Uttar Pradesh",
    city: "Kanpur",
    state: "Uttar Pradesh",
    description: "IIT Kanpur is a premier engineering institute known for excellence in research and education.",
    ranking: 4,
    establishedYear: 1959,
    accreditation: "AICTE, UGC",
    ownership: "Government",
    campusSize: "1055 acres",
    totalStudents: 7000,
    hostelFees: 110000,
    averagePackage: 2100000,
    highestPackage: 14000000,
    entranceExams: ["JEE Advanced", "GATE"],
    website: "https://www.iitk.ac.in",
    email: "info@iitk.ac.in",
    phone: "+91-512-2590151",
    isAcademicAlliance: false,
  },
  {
    name: "Indian Institute of Technology Kharagpur",
    slug: "iit-kharagpur",
    location: "Kharagpur, West Bengal",
    city: "Kharagpur",
    state: "West Bengal",
    description: "IIT Kharagpur is the first IIT and one of the largest technical institutes in India.",
    ranking: 5,
    establishedYear: 1951,
    accreditation: "AICTE, UGC",
    ownership: "Government",
    campusSize: "2100 acres",
    totalStudents: 12000,
    hostelFees: 100000,
    averagePackage: 2000000,
    highestPackage: 13000000,
    entranceExams: ["JEE Advanced", "GATE"],
    website: "https://www.iitkgp.ac.in",
    email: "info@iitkgp.ac.in",
    phone: "+91-3222-282001",
    isAcademicAlliance: false,
  },
  {
    name: "Indian Institute of Technology Roorkee",
    slug: "iit-roorkee",
    location: "Roorkee, Uttarakhand",
    city: "Roorkee",
    state: "Uttarakhand",
    description: "IIT Roorkee is one of the oldest technical institutes in India, known for engineering excellence.",
    ranking: 6,
    establishedYear: 1847,
    accreditation: "AICTE, UGC",
    ownership: "Government",
    campusSize: "365 acres",
    totalStudents: 8500,
    hostelFees: 115000,
    averagePackage: 1900000,
    highestPackage: 12000000,
    entranceExams: ["JEE Advanced", "GATE"],
    website: "https://www.iitr.ac.in",
    email: "info@iitr.ac.in",
    phone: "+91-1332-285311",
    isAcademicAlliance: false,
  },
  
  // More NITs
  {
    name: "National Institute of Technology Trichy",
    slug: "nit-trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    description: "NIT Trichy is one of the top NITs, offering quality engineering education.",
    ranking: 18,
    establishedYear: 1964,
    accreditation: "AICTE",
    ownership: "Government",
    campusSize: "800 acres",
    totalStudents: 5500,
    hostelFees: 75000,
    averagePackage: 1100000,
    highestPackage: 7000000,
    entranceExams: ["JEE Main"],
    website: "https://www.nitt.edu",
    email: "info@nitt.edu",
    phone: "+91-431-2503011",
    isAcademicAlliance: false,
  },
  {
    name: "National Institute of Technology Surathkal",
    slug: "nit-surathkal",
    location: "Surathkal, Karnataka",
    city: "Surathkal",
    state: "Karnataka",
    description: "NIT Surathkal is a premier engineering institute with excellent placement records.",
    ranking: 19,
    establishedYear: 1960,
    accreditation: "AICTE",
    ownership: "Government",
    campusSize: "295 acres",
    totalStudents: 5000,
    hostelFees: 70000,
    averagePackage: 1050000,
    highestPackage: 6500000,
    entranceExams: ["JEE Main"],
    website: "https://www.nitk.ac.in",
    email: "info@nitk.ac.in",
    phone: "+91-824-2474000",
    isAcademicAlliance: false,
  },
  
  // More IIMs
  {
    name: "Indian Institute of Management Lucknow",
    slug: "iim-lucknow",
    location: "Lucknow, Uttar Pradesh",
    city: "Lucknow",
    state: "Uttar Pradesh",
    description: "IIM Lucknow is one of India's top management institutes, known for quality MBA programs.",
    ranking: 4,
    establishedYear: 1984,
    accreditation: "AICTE",
    ownership: "Government",
    campusSize: "200 acres",
    totalStudents: 900,
    hostelFees: 140000,
    averagePackage: 2900000,
    highestPackage: 45000000,
    entranceExams: ["CAT"],
    website: "https://www.iiml.ac.in",
    email: "pgp@iiml.ac.in",
    phone: "+91-522-2734101",
    isAcademicAlliance: false,
  },
  {
    name: "Indian Institute of Management Kozhikode",
    slug: "iim-kozhikode",
    location: "Kozhikode, Kerala",
    city: "Kozhikode",
    state: "Kerala",
    description: "IIM Kozhikode is a leading management institute offering world-class business education.",
    ranking: 6,
    establishedYear: 1996,
    accreditation: "AICTE",
    ownership: "Government",
    campusSize: "112 acres",
    totalStudents: 850,
    hostelFees: 135000,
    averagePackage: 2800000,
    highestPackage: 42000000,
    entranceExams: ["CAT"],
    website: "https://www.iimk.ac.in",
    email: "pgp@iimk.ac.in",
    phone: "+91-495-2809100",
    isAcademicAlliance: false,
  },
  {
    name: "Indian Institute of Management Indore",
    slug: "iim-indore",
    location: "Indore, Madhya Pradesh",
    city: "Indore",
    state: "Madhya Pradesh",
    description: "IIM Indore is a premier B-school offering quality management education with modern infrastructure.",
    ranking: 7,
    establishedYear: 1996,
    accreditation: "AICTE",
    ownership: "Government",
    campusSize: "193 acres",
    totalStudents: 800,
    hostelFees: 130000,
    averagePackage: 2700000,
    highestPackage: 40000000,
    entranceExams: ["CAT"],
    website: "https://www.iimidr.ac.in",
    email: "pgp@iimidr.ac.in",
    phone: "+91-731-2439666",
    isAcademicAlliance: false,
  },
  
  // More Private Universities
  {
    name: "Shiv Nadar University",
    slug: "snu-noida",
    location: "Greater Noida, Uttar Pradesh",
    city: "Greater Noida",
    state: "Uttar Pradesh",
    description: "SNU is a leading private university offering quality education across multiple disciplines.",
    ranking: 40,
    establishedYear: 2011,
    accreditation: "UGC",
    ownership: "Private",
    campusSize: "286 acres",
    totalStudents: 5000,
    hostelFees: 200000,
    averagePackage: 900000,
    highestPackage: 2800000,
    entranceExams: ["SNUSAT"],
    website: "https://www.snu.edu.in",
    email: "admissions@snu.edu.in",
    phone: "+91-120-2663100",
    isAcademicAlliance: false,
  },
  {
    name: "Ashoka University",
    slug: "ashoka-university",
    location: "Sonipat, Haryana",
    city: "Sonipat",
    state: "Haryana",
    description: "Ashoka University is a leading liberal arts university offering interdisciplinary education.",
    ranking: 32,
    establishedYear: 2014,
    accreditation: "UGC",
    ownership: "Private",
    campusSize: "25 acres",
    totalStudents: 2000,
    hostelFees: 250000,
    averagePackage: 850000,
    highestPackage: 2500000,
    entranceExams: ["Ashoka Aptitude Test"],
    website: "https://www.ashoka.edu.in",
    email: "admissions@ashoka.edu.in",
    phone: "+91-130-2300000",
    isAcademicAlliance: false,
  },
  {
    name: "OP Jindal Global University",
    slug: "jgu-sonipat",
    location: "Sonipat, Haryana",
    city: "Sonipat",
    state: "Haryana",
    description: "JGU is a leading private university known for law, business, and liberal arts programs.",
    ranking: 38,
    establishedYear: 2009,
    accreditation: "UGC",
    ownership: "Private",
    campusSize: "80 acres",
    totalStudents: 6000,
    hostelFees: 220000,
    averagePackage: 800000,
    highestPackage: 2200000,
    entranceExams: ["JSAT"],
    website: "https://www.jgu.edu.in",
    email: "admissions@jgu.edu.in",
    phone: "+91-130-4091800",
    isAcademicAlliance: false,
  },
  
  // More Medical Colleges
  {
    name: "King George's Medical University",
    slug: "kgmu-lucknow",
    location: "Lucknow, Uttar Pradesh",
    city: "Lucknow",
    state: "Uttar Pradesh",
    description: "KGMU is a premier medical university offering quality medical education and healthcare.",
    ranking: 8,
    establishedYear: 1911,
    accreditation: "MCI",
    ownership: "Government",
    campusSize: "75 acres",
    totalStudents: 3000,
    hostelFees: 60000,
    averagePackage: 900000,
    highestPackage: 3500000,
    entranceExams: ["NEET"],
    website: "https://www.kgmu.org",
    email: "info@kgmu.org",
    phone: "+91-522-2257450",
    isAcademicAlliance: false,
  },
  {
    name: "Maulana Azad Medical College",
    slug: "mamc-delhi",
    location: "New Delhi",
    city: "New Delhi",
    state: "Delhi",
    description: "MAMC is a premier government medical college offering quality medical education.",
    ranking: 6,
    establishedYear: 1956,
    accreditation: "MCI",
    ownership: "Government",
    campusSize: "45 acres",
    totalStudents: 1200,
    hostelFees: 55000,
    averagePackage: 950000,
    highestPackage: 3800000,
    entranceExams: ["NEET"],
    website: "https://www.mamc.ac.in",
    email: "info@mamc.ac.in",
    phone: "+91-11-23239271",
    isAcademicAlliance: false,
  },
  
  // More Law Colleges
  {
    name: "NALSAR University of Law",
    slug: "nalsar-hyderabad",
    location: "Hyderabad, Telangana",
    city: "Hyderabad",
    state: "Telangana",
    description: "NALSAR is a premier law university consistently ranked among top law schools in India.",
    ranking: 3,
    establishedYear: 1998,
    accreditation: "UGC",
    ownership: "Government",
    campusSize: "55 acres",
    totalStudents: 700,
    hostelFees: 85000,
    averagePackage: 1300000,
    highestPackage: 18000000,
    entranceExams: ["CLAT"],
    website: "https://www.nalsar.ac.in",
    email: "admissions@nalsar.ac.in",
    phone: "+91-40-23498105",
    isAcademicAlliance: false,
  },
  {
    name: "National Law University Jodhpur",
    slug: "nluj-jodhpur",
    location: "Jodhpur, Rajasthan",
    city: "Jodhpur",
    state: "Rajasthan",
    description: "NLU Jodhpur is a premier law university offering quality legal education.",
    ranking: 4,
    establishedYear: 1999,
    accreditation: "UGC",
    ownership: "Government",
    campusSize: "50 acres",
    totalStudents: 800,
    hostelFees: 90000,
    averagePackage: 1200000,
    highestPackage: 15000000,
    entranceExams: ["CLAT"],
    website: "https://www.nlujodhpur.ac.in",
    email: "admissions@nlujodhpur.ac.in",
    phone: "+91-291-2577530",
    isAcademicAlliance: false,
  },
  
  // More Design Colleges
  {
    name: "National Institute of Fashion Technology",
    slug: "nift-delhi",
    location: "Hauz Khas, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    description: "NIFT is India's premier fashion institute offering programs in design, technology, and management.",
    ranking: 2,
    establishedYear: 1986,
    accreditation: "AICTE",
    ownership: "Government",
    campusSize: "8 acres",
    totalStudents: 1500,
    hostelFees: 100000,
    averagePackage: 700000,
    highestPackage: 2500000,
    entranceExams: ["NIFT Entrance"],
    website: "https://www.nift.ac.in",
    email: "admissions@nift.ac.in",
    phone: "+91-11-26542000",
    isAcademicAlliance: false,
  },
  {
    name: "Srishti Institute of Art, Design and Technology",
    slug: "srishti-bangalore",
    location: "Bangalore, Karnataka",
    city: "Bangalore",
    state: "Karnataka",
    description: "Srishti is a leading design institute offering innovative design education programs.",
    ranking: 6,
    establishedYear: 1996,
    accreditation: "UGC",
    ownership: "Private",
    campusSize: "15 acres",
    totalStudents: 1200,
    hostelFees: 140000,
    averagePackage: 650000,
    highestPackage: 2200000,
    entranceExams: ["Srishti Entrance"],
    website: "https://www.srishti.ac.in",
    email: "admissions@srishti.ac.in",
    phone: "+91-80-26578900",
    isAcademicAlliance: false,
  },
  
  // Additional Top Colleges
  {
    name: "St. Stephen's College",
    slug: "st-stephens-delhi",
    location: "New Delhi",
    city: "New Delhi",
    state: "Delhi",
    description: "St. Stephen's is one of India's most prestigious liberal arts colleges, part of Delhi University.",
    ranking: 5,
    establishedYear: 1881,
    accreditation: "UGC",
    ownership: "Private",
    campusSize: "5 acres",
    totalStudents: 1500,
    hostelFees: 50000,
    averagePackage: 600000,
    highestPackage: 1200000,
    entranceExams: ["DUET"],
    website: "https://www.ststephens.edu",
    email: "info@ststephens.edu",
    phone: "+91-11-27667891",
    isAcademicAlliance: false,
  },
  {
    name: "Lady Shri Ram College",
    slug: "lsr-delhi",
    location: "New Delhi",
    city: "New Delhi",
    state: "Delhi",
    description: "LSR is a premier women's college under Delhi University, known for excellence in humanities.",
    ranking: 7,
    establishedYear: 1956,
    accreditation: "UGC",
    ownership: "Private",
    campusSize: "15 acres",
    totalStudents: 2000,
    hostelFees: 60000,
    averagePackage: 550000,
    highestPackage: 1100000,
    entranceExams: ["DUET"],
    website: "https://www.lsr.edu.in",
    email: "info@lsr.edu.in",
    phone: "+91-11-26434460",
    isAcademicAlliance: false,
  },
  {
    name: "Hindu College",
    slug: "hindu-college-delhi",
    location: "New Delhi",
    city: "New Delhi",
    state: "Delhi",
    description: "Hindu College is one of the oldest and most prestigious colleges under Delhi University.",
    ranking: 8,
    establishedYear: 1899,
    accreditation: "UGC",
    ownership: "Private",
    campusSize: "25 acres",
    totalStudents: 3000,
    hostelFees: 55000,
    averagePackage: 580000,
    highestPackage: 1000000,
    entranceExams: ["DUET"],
    website: "https://www.hinducollege.ac.in",
    email: "info@hinducollege.ac.in",
    phone: "+91-11-27667891",
    isAcademicAlliance: false,
  },
]

// Course data for colleges
const courseData: Record<string, Array<{ name: string; slug: string; duration: string; fees: number; level: string; studyMode: string }>> = {
  "iit-delhi": [
    { name: "B.Tech Computer Science", slug: "btech-cs-iitd", duration: "4 years", fees: 200000, level: "undergraduate", studyMode: "offline" },
    { name: "B.Tech Mechanical Engineering", slug: "btech-me-iitd", duration: "4 years", fees: 200000, level: "undergraduate", studyMode: "offline" },
    { name: "M.Tech Computer Science", slug: "mtech-cs-iitd", duration: "2 years", fees: 150000, level: "graduate", studyMode: "offline" },
  ],
  "iit-bombay": [
    { name: "B.Tech Electrical Engineering", slug: "btech-ee-iitb", duration: "4 years", fees: 210000, level: "undergraduate", studyMode: "offline" },
    { name: "B.Tech Chemical Engineering", slug: "btech-che-iitb", duration: "4 years", fees: 210000, level: "undergraduate", studyMode: "offline" },
    { name: "M.Tech Mechanical Engineering", slug: "mtech-me-iitb", duration: "2 years", fees: 160000, level: "graduate", studyMode: "offline" },
  ],
  "iim-ahmedabad": [
    { name: "MBA", slug: "mba-iima", duration: "2 years", fees: 2300000, level: "graduate", studyMode: "offline" },
    { name: "PGP", slug: "pgp-iima", duration: "2 years", fees: 2300000, level: "graduate", studyMode: "offline" },
    { name: "Executive MBA", slug: "executive-mba-iima", duration: "1 year", fees: 3000000, level: "graduate", studyMode: "offline" },
  ],
  "iim-bangalore": [
    { name: "MBA", slug: "mba-iimb", duration: "2 years", fees: 2200000, level: "graduate", studyMode: "offline" },
    { name: "PGP", slug: "pgp-iimb", duration: "2 years", fees: 2200000, level: "graduate", studyMode: "offline" },
  ],
  "aiims-delhi": [
    { name: "MBBS", slug: "mbbs-aiims", duration: "5.5 years", fees: 5000, level: "undergraduate", studyMode: "offline" },
    { name: "MD", slug: "md-aiims", duration: "3 years", fees: 10000, level: "graduate", studyMode: "offline" },
  ],
  "nlsiu-bangalore": [
    { name: "BA LLB", slug: "ba-llb-nls", duration: "5 years", fees: 200000, level: "undergraduate", studyMode: "offline" },
    { name: "LLM", slug: "llm-nls", duration: "1 year", fees: 150000, level: "graduate", studyMode: "offline" },
  ],
  "vit-vellore": [
    { name: "B.Tech Computer Science", slug: "btech-cs-vit", duration: "4 years", fees: 180000, level: "undergraduate", studyMode: "offline" },
    { name: "MBA", slug: "mba-vit", duration: "2 years", fees: 800000, level: "graduate", studyMode: "offline" },
    { name: "BBA", slug: "bba-vit", duration: "3 years", fees: 150000, level: "undergraduate", studyMode: "offline" },
  ],
  "srm-university": [
    { name: "B.Tech", slug: "btech-srm", duration: "4 years", fees: 200000, level: "undergraduate", studyMode: "offline" },
    { name: "MBA", slug: "mba-srm", duration: "2 years", fees: 700000, level: "graduate", studyMode: "offline" },
    { name: "BBA", slug: "bba-srm", duration: "3 years", fees: 180000, level: "undergraduate", studyMode: "offline" },
  ],
  "amity-university-noida": [
    { name: "B.Tech", slug: "btech-amity", duration: "4 years", fees: 250000, level: "undergraduate", studyMode: "offline" },
    { name: "MBA", slug: "mba-amity", duration: "2 years", fees: 600000, level: "graduate", studyMode: "offline" },
    { name: "BBA", slug: "bba-amity", duration: "3 years", fees: 200000, level: "undergraduate", studyMode: "offline" },
  ],
  "lpu-jalandhar": [
    { name: "B.Tech", slug: "btech-lpu", duration: "4 years", fees: 180000, level: "undergraduate", studyMode: "offline" },
    { name: "MBA", slug: "mba-lpu", duration: "2 years", fees: 500000, level: "graduate", studyMode: "offline" },
    { name: "BBA", slug: "bba-lpu", duration: "3 years", fees: 150000, level: "undergraduate", studyMode: "offline" },
  ],
  "isbr-business-school-bangalore": [
    { name: "MBA", slug: "mba-isbr", duration: "2 years", fees: 800000, level: "graduate", studyMode: "offline" },
    { name: "PGDM", slug: "pgdm-isbr", duration: "2 years", fees: 750000, level: "graduate", studyMode: "offline" },
    { name: "BBA", slug: "bba-isbr", duration: "3 years", fees: 200000, level: "undergraduate", studyMode: "offline" },
  ],
}

async function seedComprehensive() {
  try {
    console.log("🌱 Seeding comprehensive college data with all comparison fields...\n")

    let insertedCount = 0
    let updatedCount = 0

    for (const college of comprehensiveColleges) {
      try {
        // Check if college exists
        const existing = await db
          .select()
          .from(colleges)
          .where(eq(colleges.slug, college.slug))
          .limit(1)

        if (existing.length > 0) {
          // Update existing college with comprehensive data
          await db
            .update(colleges)
            .set({
              name: college.name,
              location: college.location,
              city: college.city,
              state: college.state,
              description: college.description,
              ranking: college.ranking,
              establishedYear: college.establishedYear,
              accreditation: college.accreditation,
              ownership: college.ownership,
              campusSize: college.campusSize,
              totalStudents: college.totalStudents,
              hostelFees: college.hostelFees,
              averagePackage: college.averagePackage,
              highestPackage: college.highestPackage,
              entranceExams: college.entranceExams,
              website: college.website,
              email: college.email,
              phone: college.phone,
              isAcademicAlliance: college.isAcademicAlliance,
              updatedAt: new Date(),
            })
            .where(eq(colleges.slug, college.slug))
          
          updatedCount++
          console.log(`🔄 Updated: ${college.name}`)
        } else {
          // Insert new college
          await db.insert(colleges).values({
            name: college.name,
            slug: college.slug,
            location: college.location,
            city: college.city,
            state: college.state,
            country: "India",
            description: college.description,
            ranking: college.ranking,
            establishedYear: college.establishedYear,
            accreditation: college.accreditation,
            ownership: college.ownership,
            campusSize: college.campusSize,
            totalStudents: college.totalStudents,
            hostelFees: college.hostelFees,
            averagePackage: college.averagePackage,
            highestPackage: college.highestPackage,
            entranceExams: college.entranceExams,
            website: college.website,
            email: college.email,
            phone: college.phone,
            isAcademicAlliance: college.isAcademicAlliance,
          })
          
          insertedCount++
          console.log(`✅ Inserted: ${college.name}`)
        }

        // Add courses for this college
        const collegeCourses = courseData[college.slug]
        if (collegeCourses) {
          // Get college ID
          const [collegeRecord] = await db
            .select()
            .from(colleges)
            .where(eq(colleges.slug, college.slug))
            .limit(1)

          if (collegeRecord) {
            for (const courseInfo of collegeCourses) {
              try {
                // Check if course exists
                const existingCourse = await db
                  .select()
                  .from(courses)
                  .where(eq(courses.slug, courseInfo.slug))
                  .limit(1)

                if (existingCourse.length === 0) {
                  await db.insert(courses).values({
                    name: courseInfo.name,
                    slug: courseInfo.slug,
                    collegeId: collegeRecord.id,
                    duration: courseInfo.duration,
                    fees: courseInfo.fees,
                    feesCurrency: "INR",
                    level: courseInfo.level,
                    studyMode: courseInfo.studyMode,
                    description: `${courseInfo.name} at ${college.name}`,
                  })
                  console.log(`  ✅ Course: ${courseInfo.name}`)
                }
              } catch (error: any) {
                if (error?.code !== "23505") {
                  console.error(`  ❌ Error inserting course ${courseInfo.name}:`, error.message)
                }
              }
            }
          }
        }
      } catch (error: any) {
        if (error?.code !== "23505") {
          console.error(`❌ Error with ${college.name}:`, error.message)
        }
      }
    }

    console.log("\n✨ Comprehensive seeding completed!")
    console.log(`📊 Summary:`)
    console.log(`   - Colleges inserted: ${insertedCount}`)
    console.log(`   - Colleges updated: ${updatedCount}`)
    console.log(`   - Total colleges processed: ${comprehensiveColleges.length}`)
  } catch (error) {
    console.error("❌ Comprehensive seeding failed:", error)
    throw error
  }
}

// Run seed
seedComprehensive()
  .then(() => {
    console.log("✅ Comprehensive seed script completed successfully")
    process.exit(0)
  })
  .catch((error) => {
    console.error("❌ Comprehensive seed script failed:", error)
    process.exit(1)
  })

export { seedComprehensive }

